### ISSUE TITLE
[1.13.0 Regression] Views doesn't use attributeBindings

### ISSUE THREAD

**Issue by marcemira** [emberjs/ember.js#11480]
Hello, I have been using attributeBindings: ['id'] in order to assign id to my route's view. This way I can "namespace" css by route. This has stopped working since 1.13.0 (same as in components). I understand the reasons here https://github.com/emberjs/ember.js/pull/11141 , but it's not valid for a routes view, since it's not written in templates. Am I not folliwing the "right way" or it's really a regression (please feel free to replace the title if not)? Thanks!

**Comment by rwjblue** [comment]
Confirmed that `attributeBinding` for `id` is not working. Here is a [JSBin demo](http://emberjs.jsbin.com/rwjblue/578/edit?html,js,output).

**Comment by marcemira** [comment]
@rwjblue here's a JSBin demo: http://emberjs.jsbin.com/tokona/edit?html,js,output

**Comment by mixonic** [comment]
I do not suggest using an `id` binding like this, but it seems like a regression.

**Comment by marcemira** [comment]
Any progress on this issue?

**Comment by nybblr** [comment]
Same issue here on Ember 1.13.9: I have a component like such:

```javascript
export default Ember.Component.extend({
  tagName: 'a',
  href: '#',
  id: 'my-component',
  attributeBindings: ['href', 'id'],
  click: function(event) {
    event.preventDefault();
    console.log("CLICK");
  }
}
```

Interestingly, the `id` attributeBinding *breaks all event handlers* (e.g. `click` never fires), but removing just `id` from the `attributeBindings` makes events work again.

**Comment by nybblr** [comment]
Ah, I get what's happening here. Just to make sure it wasn't related to the concatenatedProperties bug resolved in 1.13.10, I upgraded. Same problem.

But when you attributeBind to `id`, it overrides the unique `ember256` id that is added, presumably for binding those event handlers.

Is there a workaround for this or more relevant issue?

**Comment by rwjblue** [comment]
The demo JSBin seems to be working properly on release-1-13 branch: http://emberjs.jsbin.com/tufosiz/edit?js,output.

**Comment by rwjblue** [comment]
Was fixed in https://github.com/emberjs/ember.js/pull/11889.

**Comment by nybblr** [comment]
#11889 did fix not being able to bind to `id` at all, but seems to break any event handlers (e.g. a click handler).

Try adding a "click" handler to your example (e.g. an alert) and notice it doesn't fire when attributeBindings includes `id`. Drop `id` and try again (I had to change the CSS styling to target the class instead of ID so I could still see the square) and notice the `click` handler works now.

**Comment by runspired** [comment]
it appears you can get around this bug by binding like this
```
attributeBindings: ['id:id', 'href:href']
```

**Comment by Serabe** [comment]
@rwjblue this is still happening in [2.5.0](https://ember-twiddle.com/94a6e3f1836feff408da011505a2ea8a?openFiles=twiddle.json%2Ctemplates.components.attr-test.hbs) when the attribute being passed is static. Check in previous twiddle that it works for `{{attr-test}}` and `{{attr-test rows=externalRows}}` but not for `{{attr-test rows=4}}`.

**Comment by Serabe** [comment]
Seems fixed in 2.12 ([Ember-Twiddle](https://ember-twiddle.com/8ff09a1a5cbf363625c6354ace52fe5c?openFiles=twiddle.json%2Ctemplates.components.attr-test.hbs)). Closing this.

Thank you everyone!
