### ISSUE TITLE
Possible Regression: Query params alias behavior changed?

### ISSUE THREAD

**Issue by wagenet** [emberjs/ember.js#12102]
In 1.13.8 I had the following code:

```js
// controller.js
  queryParams: {
    displayMode: "mode"
  }

// route.js
  queryParams: {
    mode: {
      replace: true
    }
  }
```

However, this started giving an error in 2.0:

> You're not allowed to have more than one controller property map to the same query param key, but both `app:displayMode` and `app:mode` map to `mode`. You can fix this by mapping one of the controller properties to a different query param key via the `as` config option, e.g. `displayMode: { as: 'other-displayMode' }`

Changing the route to the following solved the issue.

```js
  queryParams: {
    displayMode: {
      replace: true
    }
  }
```

**Comment by rwjblue** [comment]
Can you provide a reproduction ember-twiddle / JSBin ?

**Comment by SaladFork** [comment]
Reproduction:
 * [**2.0.0 JSBin**](http://emberjs.jsbin.com/kozexitehu/1/edit?html,js,output): Change input to cause error
 * [**1.13.8 JSBin**](http://emberjs.jsbin.com/kozexitehu/1/edit?html,js,output): Identical code but different Ember version, no error

**Comment by JKGisMe** [comment]
Not sure if this is the same or something different but here is a Twiddle showing the queryParams alias doesn't work at all in 1.13.8. Maybe that's why there was no error in 1.13.8.

If you have:
```javascript
 queryParams: ['color', {perPage: 'per_page'}, {firstName: 'first_name'}],
``` 
Then `per_page` and `first_name` is never used. 

http://ember-twiddle.com/5e1e9fe67b616837bf97

**Comment by lolmaus** [comment]
Possibly related: #11592.

**Comment by pixelhandler** [comment]
another related/duplicate issue: #11977

**Comment by v3ss0n** [comment]
same problem. 
SO it is a bug?

**Comment by raytiley** [comment]
I think https://github.com/emberjs/ember.js/pull/13273 will address this /CC @rwjblue

**Comment by rwjblue** [comment]
Thanks @raytiley.  I'm going to close this for now, but I would love to land a new query params test to ensure we do not regress here in the future.  Feel free to ping me if you would like help on how that might look...

**Comment by v3ss0n** [comment]
so this is fixed in beta 2.7 merged ?

**Comment by rwjblue** [comment]
Please test to confirm, but yes that is what we believe.

**Comment by v3ss0n** [comment]
ok i will test when 2.7 released , can't upgrade coz the project with 2.6 version is close to release now.

**Comment by swquinn** [comment]
Maybe I'm not understanding the mapping of query parameters correctly or I have it backwards, but on 2.7 I have two routes (`topic` and `reply`) which are registered with the router with `reply` being below `topic`, e.g.:


```
  ...
  this.route('topic', { path: ':topic' }, function() {
    this.route('reply', { path: 'reply' });
  });
  ...
```

And encounter this assertion regularly if `topic` and `reply` share the same query parameter, in this case `post`. On the `topic` route/controller `post` should "jump" the user to the post in question and on `reply` should supply quoted text to pre-fill in the reply's text field. After first receiving the warning:

> **Assertion Failed:** You're not allowed to have more than one controller property map to the same query param key, but both `community.forum.topics.topic:post` and `community.forum.topics.topic.reply:post` map to `post`. You can fix this by mapping one of the controller properties to a different query param key via the `as` config option, e.g. `post: { as: 'post' }`

I tried changing my query parameter definitions to the following:

```
// routes/community/forum/topics/topic.js
  queryParams: {
    post: { refreshModel: true }
  }

// routes/community/forum/topics/topic/reply.js
  queryParams: {
    post: { refreshModel: true }
  }
```

... and the controllers to:

```
// controllers/community/forum/topics/topic.js
  queryParams: [
    { viewPost: 'post' }
  ]

// controllers/community/forum/topics/topic/reply.js
  queryParams: [
    { replyPost: 'post' }
  ]
```

But still receive:

> **Assertion Failed:** You're not allowed to have more than one controller property map to the same query param key, but both `community.forum.topics.topic:viewPost` and `community.forum.topics.topic.reply:replyPost` map to `post`. You can fix this by mapping one of the controller properties to a different query param key via the `as` config option, e.g. `viewPost: { as: 'other-viewPost' }`

My understanding of the guide, in particular the section on [mapping a controller's property to a different query param key](https://guides.emberjs.com/v2.7.0/routing/query-params/#toc_map-a-controller-s-property-to-a-different-query-param-key), was that within the controller I am aliasing a bound property to a query parameter, e.g. `viewPost` and `replyPost` both bind to the `post` query parameter. This doesn't seem possible? The error seems to suggest I can't have two routes which use the same query parameter if they are related hierarchically to one another.

**Comment by omairvaiyani** [comment]
In case anyone else is still having this issue (I sure just did), here's how I fixed it.

Just upgraded to 2.10.2 when this assertion came up.

```Assertion Failed: You're not allowed to have more than one controller property map to the same query param key, but both ...```

Turns out, if a controller has ```queryParams``` defined, it cannot be used by multiple routes, or be extended. Or at least, that's how I managed to resolve the error. 

E.g. ```HomeController``` had query params, ```HomeIndexRoute``` had the property ```controllerName: 'home```. Instead, I now made ```HomeIndexController``` and injected ```HomeController``` into it to utilise the main controller logic.

Hope that helps others coming here from Google!
