### ISSUE TITLE
ES5 getters on an Ember.Object only ever return first computed value

### ISSUE THREAD

**Issue by chrisjshull** [emberjs/ember.js#12940]
```js
var i = 0;
var obj = Ember.Object.extend({
    get index() {
        return i++;
    }
}).create();
console.log(obj.index); // 0
console.log(obj.index); // 0 -> should be 1
```

Compare to not extending Ember.Object:

```js
var i = 0;
var obj = {
    get index() {
        return i++;
    }
};
console.log(obj.index); // 0
console.log(obj.index); // 1
```

Ember 2.3.0

**Comment by chrisjshull** [comment]
Oh, and just in case people were curious, using `.get` doesn't help:
```js
var i = 0;
var obj = Ember.Object.extend({
    get index() {
        return i++;
    }
}).create();
console.log(obj.get('index'));
console.log(obj.get('index'));
```

I wouldn't expect it to though. It looks like Ember is doing a 1-time evaluation of the property at mergeMixins time. Anything after that resolves to that "cached" value.

**Comment by stefanpenner** [comment]
fixed (for objects, not mixins) in master

**Comment by chrisjshull** [comment]
awesome! any chance of a commit or PR link?

**Comment by stefanpenner** [comment]
https://github.com/emberjs/ember.js/pull/12491

**Comment by rwjblue** [comment]
I believe it is also included in 2.4.0-beta.2

**Comment by chrisjshull** [comment]
Can we reopen this? The snippet above is not fixed (Ember 2.8.0).
