### ISSUE TITLE
Cannot convert object to primitive value

### ISSUE THREAD

**Issue by ef4** [emberjs/ember.js#14738]
This is similar to https://github.com/emberjs/ember.js/issues/14187, but I have a reproduction in Ember 2.10 with no addons:

https://ember-twiddle.com/4df2d62bf5f1c05bd74086dc79326020?openFiles=components.my-component.js%2C

The critical ingredient seems to be that I am taking an object created by the `hash` helper, putting it inside an `Array`, and passing the array into another component. When such an array hits `toString` it causes an exception.

(It's hitting `toString` in the first place to support an assertion.)

**Comment by Sinled** [comment]
Have the same problem, when passing objects constructed with `hash` as positional params to component

**Comment by iStefo** [comment]
I have a similar problem when passing a hash into the `array` helper from https://github.com/DockYard/ember-composable-helpers.

Twiddle that reproduces the issue (note how myComponent.totalLength can't be computed!): https://ember-twiddle.com/b886a7c23774720188df41e9967aa443?openFiles=templates.application.hbs%2C

"Fixed" by replying the `hash` helper with a very simple `my-hash` helper that returns a full object instead of the EmptyObject that Ember itself uses: (note how now totalLength is shown):
https://ember-twiddle.com/208688934ca9599e8607045d3e067fde?openFiles=templates.application.hbs%2C

**Comment by thedig** [comment]
Also bumping up against this issue. It appears `hash` returns an `Object` in 2.7.x, 2.8.x, 2.9.x, but 2.10.1 returns an `EmptyObject`. This caused issues with a library looking to call `hasOwnProperty` on it. Is there a design reason for `EmptyObject` to be used?

**Comment by morhook** [comment]
In Ember 2.11 the problem is still there. You can select 'release' on ember-twiddle to load that version. @iStefo 

https://ember-twiddle.com/4df2d62bf5f1c05bd74086dc79326020?openFiles=twiddle.json%2C

On my application is also hitting me this problem with a `hash` I've created on the `.hbs` too.

**Comment by gabrielgrant** [comment]
Hitting this too while using `hash` helper. Anyone have a suggested work-around?

**Comment by gabrielgrant** [comment]
Specifically, this seems to error out when I pass the output of a helper into the `hash` helper, but not when passing in a string (which makes me think I'm misunderstanding the root cause -- I'd have thought it would fail in either case?)

Full traceback: 

```
jQuery.Deferred exception: Cannot convert object to primitive value TypeError: Cannot convert object to primitive value
    at Array.toString (native)
    at Object.toString (http://localhost:4200/assets/vendor.js:55320:18)
    at Object.set (http://localhost:4200/assets/vendor.js:36891:131)
    at http://localhost:4200/assets/vendor.js:37754:33
    at Object.changeProperties (http://localhost:4200/assets/vendor.js:36679:16)
    at Object.setProperties (http://localhost:4200/assets/vendor.js:37747:32)
    at Class.setProperties (http://localhost:4200/assets/vendor.js:49593:26)
    at CurlyComponentManager.update (http://localhost:4200/assets/vendor.js:27614:19)
    at UpdateComponentOpcode.evaluate (http://localhost:4200/assets/vendor.js:62099:21)
    at UpdatingVM.execute (http://localhost:4200/assets/vendor.js:69010:24) undefined
ember.debug.js:40465 Uncaught TypeError: Cannot convert object to primitive value
toString	@	ember.debug.js:40465
set	@	ember.debug.js:22036
(anonymous function)	@	ember.debug.js:22899
changeProperties	@	ember.debug.js:21824
setProperties	@	ember.debug.js:22892
setProperties	@	ember.debug.js:34738
update	@	ember.debug.js:12759
evaluate	@	ember.debug.js:47244
execute	@	ember.debug.js:54155
rerender	@	ember.debug.js:54094
_this.render	@	ember.debug.js:11854
runInTransaction	@	ember.debug.js:23035
_renderRoots	@	ember.debug.js:12115
_renderRootsTransaction	@	ember.debug.js:12153
_revalidate	@	ember.debug.js:12192
invoke	@	ember.debug.js:336
flush	@	ember.debug.js:404
flush	@	ember.debug.js:528
end	@	ember.debug.js:598
run	@	ember.debug.js:721
join	@	ember.debug.js:743
loopEnd	@	ember.debug.js:11936
_trigger	@	ember.debug.js:633
end	@	ember.debug.js:609
run	@	ember.debug.js:721
join	@	ember.debug.js:743
run.join	@	ember.debug.js:22289
(anonymous function)	@	ember.debug.js:22352
mightThrow	@	jquery.js:3570
process	@	jquery.js:3638
```

**Comment by morhook** [comment]
@gabrielgrant you can create a helper `my-hash`, like @iStefo suggested in his twiddle:

```js
import Ember from 'ember';

export function myHash(params, hash) {
  return Object.assign({}, hash);
}

export default Ember.Helper.helper(myHash);
```

**Comment by gabrielgrant** [comment]
@caseklim @rwjblue have a workaround in this (possibly duplicate?) issue:  https://github.com/emberjs/ember.js/issues/14922#issuecomment-279037935

**Comment by caseklim** [comment]
@gabrielgrant mhm, looks like my issue is a duplicate of this one. I simplified the helper I posted in that issue to one that is very similar to @morhook's:
```
import Ember from 'ember';

export function hashObj(_, obj) {
  return Ember.merge({}, obj);
}

export default Helper.helper(hashObj);
```

**Comment by rwjblue** [comment]
@gabrielgrant / @caseklim - Good spot, I didn't notice that both were describing the same issue.  I'll close #14922 for now and we can track the issue here.
