### ISSUE TITLE
RouterService forces model to refresh when queryParams unchanged

### ISSUE THREAD

**Issue by ro0gr** [emberjs/ember.js#16349]
I have a query param defined in the controller and set it up to `refreshModel` in the route.

Then I inject the `router` service to the component and trigger a transition just with a sub-route name(no passing query params).

**expected**: since I haven't passed [`Ember.DEFAULT_VALUE`](https://github.com/emberjs/rfcs/blob/master/text/0095-router-service.md#query-parameter-semantics) query params should be preserved during the transition.

**actual**:  query param treated as changed which causes the parent route to reload.

Reproduction: https://ember-twiddle.com/efda3c9e57835c987404a8f5968c7579?openFiles=routes.application.js%2C&route=%2Fin

**Comment by ro0gr** [comment]
@ef4 am I right by considering this behavior as a bug?

**Comment by ro0gr** [comment]
The other interesting thing which appears in the twiddle is that default `queryParams` are reflected in the URL only after the second `router.transitionTo()` invocation.

[Router RFC](https://github.com/emberjs/rfcs/blob/master/text/0095-router-service.md#query-parameter-semantics) sheds some light on the default query params semantics. But it's unclear how the  `transtitionTo` should behave when no query params are passed in.

**Comment by ro0gr** [comment]
This issue is very similar to https://github.com/emberjs/ember.js/issues/15801. It may have the same root cause. However this issue is reproducible without passing any query params to the `router.transtionTo()`

**Comment by Exelord** [comment]
I've got the similar issue right now. And I found a problem. If your QP default is a `null` it's always visible as a change for the router which triggers the model reloading. Try to change it to `undefined` or other, then it should not reload the model.

**Comment by ro0gr** [comment]
@Exelord actually in the twiddle I have a non-empty string as a default QP value.

**Comment by rwjblue** [comment]
I believe that this is addressed now, @chadhietala may be able to confirm.

**Comment by ro0gr** [comment]
I've just verified it against ember-source@3.6(cause its release notes say: `Final stage of the router service RFC (see emberjs/rfcs#95`) and the issue seems to be persited.

Here is a [repo with reproduction](https://github.com/ro0gr/qparams-repro) for ember-source@3.6 if helpful.

**Comment by arun-jerry** [comment]
is there a work around for this? other than reloading the window.

**Comment by aaxelb** [comment]
i tried chasing this down (making sense of the [various](https://github.com/emberjs/ember.js/blob/2052e60418a92b9bbac86c9afc2e82fd70cdccb9/packages/%40ember/-internals/routing/lib/services/router.ts#L130) [special](https://github.com/emberjs/ember.js/blob/0efdae9456c24339a60947e4155ff471945e6229/packages/%40ember/-internals/routing/lib/system/route.ts#L2582) [cases](https://github.com/emberjs/ember.js/blob/93b08fe7afb1034785f968f0095721b291df5054/packages/%40ember/-internals/routing/lib/system/router.ts#L896-L898) for transitions originating from the router service) and all i got were some failing tests: https://github.com/emberjs/ember.js/pull/18579

**Comment by gokatz** [comment]
Still facing this issue when using QPs (`refreshModel`) with router service's `transitionTo` API. Any help on this?

**Comment by algodave** [comment]
> Still facing this issue when using QPs (`refreshModel`) with router service's `transitionTo` API. Any help on this?
> 
> Using Ember source and CLI: 3.22

Same issue here

**Comment by eodb** [comment]
We also ran into this issue. The workaround we are using in the meantime is not to use the QP's default value and always set it to a different value (with the drawback that it always appears in the url).

**Comment by Techn1x** [comment]
Still an issue on Ember 4.4.4 and Ember 4.9.2 :cry:

**Comment by PowerP** [comment]
This is terrible, why is this not fixed yet.

**Comment by locks** [comment]
@PowerP could you submit a fix? I'll make sure to get it reviewed as soon as possible!

**Comment by mkszepp** [comment]
Still an issue on Ember 5.4.1 😭

**Comment by NullVoxPopuli** [comment]
Resolved by https://github.com/emberjs/ember.js/pull/21409
