### ISSUE TITLE
ember-source

### ISSUE THREAD

**Issue by poplevente** [emberjs/ember.js#16827]
Hi Guys,

after updating ember-source from 3.2.2 to 3.3.0, i get the following errors:

Warning: ignoring input sourcemap for vendor/ember/ember.debug.js because ENOENT: no such file or directory
Warning: ignoring input sourcemap for vendor/ember/ember-testing.js because ENOENT: no such file or directory

anyone else having this? if i go back to 3.2.2 the warning is gone.

**Comment by rwjblue** [comment]
I haven't seen this issue yet, can you provide a demo reproduction?

**Comment by poplevente** [comment]
I just hit npm install. i had to update another package and saw this after a full npm install. when i go back to 3.2.2 ember source, the error is gone.

**Comment by HerveSeger** [comment]
I have exactly the same problem with a regular `ember serve` after upgrading from 3.0.0 to 3.3.1:

```
Warning: ignoring input sourcemap for vendor/ember/ember.debug.js because ENOENT: no such file or directory, open 'c:\projects\git\insurance-online-ui\tmp\source_map_concat-input_base_path-XDYu3Wbd.tmp\vendor\ember\index.js.map'
Warning: ignoring input sourcemap for vendor/ember/ember-testing.js because ENOENT: no such file or directory, open 'c:\projects\git\insurance-online-ui\tmp\source_map_concat-input_base_path-DRNeZdj4.tmp\vendor\ember\testing.js.map'
```

I am on Windows 7.

**Comment by pixelhandler** [comment]
@poplevente @HerveSeger were you able to resolve this issue? Does clearing the node_modules directory help?

**Comment by poplevente** [comment]
@pixelhandler this is solved in the last version as far as i see, so the issue was known.

**Comment by buschtoens** [comment]
Maybe this is related to / a dupe of #16881, seeing that downgrading to `3.2.2` fixes the issue?

**Comment by poplevente** [comment]
could be. downgrading also worked, but as i see the last version is also fine.

**Comment by HerveSeger** [comment]
Hi.

@pixelhandler 
The warnings are gone. I just checked today.

I had to run `yarn` a few times in the  past weeks so maybe a dependency has been upgraded?
I do not know when (or why) the warnings have disappeared but the fact is that they are gone.

**Comment by kmoe** [comment]
This is still an issue in `3.3.0`. To see why, download `ember-source@3.3.0` and look at `dist/ember.prod.js`. This file has multiple declarations of the form

```
//# sourceMappingURL=...
```

which is invalid. Please see #16881 for details of why this breaks the sourcemap build.

**Comment by kmoe** [comment]
@rwjblue The repro case is in https://github.com/emberjs/ember.js/issues/16844 (closed), but here is a copy:

## Steps to reproduce

1. Create a new ember project 
```
$ ember new abc --skip-git
$ cd abc
```

2. Install the latest version of ember-source
```
$ npm i --save-dev ember-source@3.4.0
```

3. Add sourcemaps to the build
```
$ sed -i '/\/\/ Add options here/a sourcemaps:{enabled:true}' ember-cli-build.js
```

4. Build for production
```
$ npm run build -- --environment=production
```

## Results
```
> ember build "--environment=production"

⠧ Building[WARN] (broccoli-uglify-sourcemap) "index.js.map" referenced in "assets/vendor.js" could not be found
cleaning up...
Built project successfully. Stored in "dist/".
File sizes:
 - dist/assets/abc-94dbdc62c3439ef82228bb04ee7cce04.js: 4.34 KB (1.36 KB gzipped)
 - dist/assets/abc-d41d8cd98f00b204e9800998ecf8427e.css: 0 B
 - dist/assets/vendor-864f4cfe6a0b732a7ba7c5e02bfbb420.js: 732.86 KB (192.92 KB gzipped)
 - dist/assets/vendor-d41d8cd98f00b204e9800998ecf8427e.css: 0 B
```

Note the error message indicating that the `assets/vendor.js` sourcemap could not be built.

**Comment by rwjblue** [comment]
Closing in favor of https://github.com/emberjs/ember.js/issues/16881
