### ISSUE TITLE
[Bug] Ember 3.20.4 breaks @sort

### ISSUE THREAD

**Issue by st-h** [emberjs/ember.js#19101]
### 🐞 Describe the Bug
I have a ember data one to many relationship:

`@hasMany('project/invite', {async: false}) invited!: EmberArray<ProjectInviteModel>;`

When I delete one of those `ProjectInviteModel` like:

`await invite.destroyRecord();`

and there is a dependent sort:
```
  invitationsSortKeys = ['email'];
  @sort('model.invited', 'invitationsSortKeys')
  sortedInvitations;
```

`sortedInvitations` is no longer updated when the record is deleted. It just keeps the old (now invalid) value. Exactly the same issue happens when using https://pzuraq.github.io/macro-decorators/

This has been working fine up to Ember 3.20.3.

 
### 🔬 Minimal Reproduction
Describe steps to reproduce. If possible, please, share a link with a minimal reproduction.
likely related to #19097 

### 🌍 Environment

- Ember: 3.20.4
- Node.js/npm: v14.7.0
- OS: linux / macOS (not tested running ember on windows)
- Browser: does not matter

**Comment by jonathannewman** [comment]
We ran into this too.  We found that a work around is to replace the use of `@sort` with a computed that declares the proper dependencies and sorts the result.  

Certainly not ideal, but by doing so, we were able to leverage `Intl.Collator` for comparison over the collection instead of the relatively slow `localeCompare` that is used internally for some small performance wins.

**Comment by rwjblue** [comment]
Thank you for reporting! If someone has the time, a failing test case would be really helpful to us (to help ensure we get it fixed, and prevent future regressions). Something like this test (which passes ATM 🤔): 

https://github.com/emberjs/ember.js/blob/93fb76515ec4b808962ea68ae95b11ead6986681/packages/%40ember/object/tests/computed/reduce_computed_macros_test.js#L1669-L1683

**Comment by jonathannewman** [comment]
I've been trying to reproduce it in the unit tests, but haven't been successful.  
The issues we saw were all about templates not re-rendering when the content changed.  Any suggestions about where to explore a testing in that avenue?

**Comment by pzuraq** [comment]
This is likely because `@sort` relies on autotracking (previously it relied on observers), so it has the same issue templates had with not updating. #19111 should fix this as well.

**Comment by Kilowhisky** [comment]
I'm experiencing the same issue @jonathannewman described where updates are not propagated. In particular i'm seeing it related to running `action=(action (mut model.edmodel.hasmany))` with ember `3.20.4` and `3.20.5`.  Backing back down to `3.20.3` resolves it. 

This sounds related enough to not need a new issue, but i may be wrong here.

**Comment by snewcomer** [comment]
@st-h Mind trying ember-data `3.22.0`?  I added tests and a fix that should match your behaviour here.

**Comment by st-h** [comment]
@snewcomer Thanks. Will give it a try. Just noticed though, that the offending @sort is now already migrated to native classes without the `@sort`:

```
  get sortedInvitations() {
    return this.args.invited?.sortBy('email', 'user').reverse();
  };
```

But I still have a few @sort annotations :)

**Comment by st-h** [comment]
I finally found some time to test the upgrade and so far I haven't noticed any issues. 👍

**Comment by sandstrom** [comment]
> I finally found some time to test the upgrade and so far I haven't noticed any issues. 👍
