### ISSUE TITLE
[Bug] [Canary] `{{@component}}` template compiler error

### ISSUE THREAD

**Issue by buschtoens** [emberjs/ember.js#19313]
### 🐞 Describe the Bug

It seems that, if a template includes `{{@component}}`, the latest Ember canary fails with this error:

```
{{component}} requires a component definition or identifier as its first positional parameter, did not receive any parameters.
(error occurred in 'ember-cli-addon-docs/components/api/x-component/template.hbs' @ line 1 : column 61)
```

```hbs
<h1 class="docs-h1" data-test-component-name>{{@component.name}}</h1>
```

https://github.com/ember-learn/ember-cli-addon-docs/blob/master/addon/components/api/x-component/template.hbs#L1

### 🔬 Minimal Reproduction

https://github.com/ember-intl/ember-intl/runs/1571041877#step:5:80

### 🌍 Environment

- Ember: latest canary

**Comment by rwjblue** [comment]
Thank you for reporting!!!

**Comment by rwjblue** [comment]
@buschtoens - I believe this should have been fixed by https://github.com/emberjs/ember.js/pull/19317, the error was introduced by an Ember side AST transform.

Can you double check?

**Comment by buschtoens** [comment]
Sure! I've just installed the 9b9ec9594c73cd3b8a6af06e415cd2c1398b8774 canary by updating the `package.json` entry for `ember-source` to `https://s3.amazonaws.com/builds.emberjs.com/canary/shas/9b9ec9594c73cd3b8a6af06e415cd2c1398b8774.tgz`. I also did a nombom and regenerated the `yarn.lock` file.

The error still persists:

```
Template Compiler Error (broccoli-persistent-filter:TemplateCompiler) in ember-cli-addon-docs/components/api/x-component/template.hbs

(component) requires a component definition or identifier as its first positional parameter, did not receive any parameters.: (error occurred in 'ember-cli-addon-docs/components/api/x-component/template.hbs' @ line 1 : column 61)
```

```
  - broccoliBuilderErrorStack: SyntaxError: (component) requires a component definition or identifier as its first positional parameter, did not receive any parameters.: (error occurred in 'ember-cli-addon-docs/components/api/x-component/template.hbs' @ line 1 : column 61)
    at generateSyntaxError (/Users/jan/open-source/ember-intl/node_modules/ember-source/dist/ember-template-compiler.js:11330:17)
    at Object.assert (/Users/jan/open-source/ember-intl/node_modules/ember-source/dist/ember-template-compiler.js:3656:52)
    at KeywordImpl.translate (/Users/jan/open-source/ember-intl/node_modules/ember-source/dist/ember-template-compiler.js:3199:35)
    at Keywords.translate (/Users/jan/open-source/ember-intl/node_modules/ember-source/dist/ember-template-compiler.js:3266:34)
    at NormalizationStatements.AppendContent (/Users/jan/open-source/ember-intl/node_modules/ember-source/dist/ember-template-compiler.js:4884:40)
    at NormalizationStatements.visit (/Users/jan/open-source/ember-intl/node_modules/ember-source/dist/ember-template-compiler.js:4803:23)
    at /Users/jan/open-source/ember-intl/node_modules/ember-source/dist/ember-template-compiler.js:4789:28
    at Array.map (<anonymous>:null:null)
    at NormalizationStatements.visitList (/Users/jan/open-source/ember-intl/node_modules/ember-source/dist/ember-template-compiler.js:4788:36)
    at ClassifiedSimpleElement.toStatement (/Users/jan/open-source/ember-intl/node_modules/ember-source/dist/ember-template-compiler.js:4767:30)
    at /Users/jan/open-source/ember-intl/node_modules/ember-source/dist/ember-template-compiler.js:4546:32
    at OkImpl.andThen (/Users/jan/open-source/ember-intl/node_modules/ember-source/dist/ember-template-compiler.js:3035:14)
    at ClassifiedElement.toStatement (/Users/jan/open-source/ember-intl/node_modules/ember-source/dist/ember-template-compiler.js:4545:29)
    at NormalizationStatements.SimpleElement (/Users/jan/open-source/ember-intl/node_modules/ember-source/dist/ember-template-compiler.js:4874:132)
    at NormalizationStatements.visit (/Users/jan/open-source/ember-intl/node_modules/ember-source/dist/ember-template-compiler.js:4818:23)
    at /Users/jan/open-source/ember-intl/node_modules/ember-source/dist/ember-template-compiler.js:4789:28
    at Array.map (<anonymous>:null:null)
    at NormalizationStatements.visitList (/Users/jan/open-source/ember-intl/node_modules/ember-source/dist/ember-template-compiler.js:4788:36)
    at normalize$1 (/Users/jan/open-source/ember-intl/node_modules/ember-source/dist/ember-template-compiler.js:5034:28)
    at precompileJSON (/Users/jan/open-source/ember-intl/node_modules/ember-source/dist/ember-template-compiler.js:6060:17)
    at precompile (/Users/jan/open-source/ember-intl/node_modules/ember-source/dist/ember-template-compiler.js:6096:27)
    at Object.precompile (/Users/jan/open-source/ember-intl/node_modules/ember-source/dist/ember-template-compiler.js:20297:37)
    at Object.template (/Users/jan/open-source/ember-intl/node_modules/ember-cli-addon-docs/node_modules/ember-cli-htmlbars/lib/utils.js:179:38)
    at TemplateCompiler.processString (/Users/jan/open-source/ember-intl/node_modules/ember-cli-addon-docs/node_modules/ember-cli-htmlbars/lib/template-compiler-plugin.js:72:15)
    at Promise.then.output (/Users/jan/open-source/ember-intl/node_modules/broccoli-persistent-filter/lib/strategies/persistent.js:56:23)
    at initializePromise (/Users/jan/open-source/ember-intl/node_modules/rsvp/dist/rsvp.js:523:7)
    at new Promise (/Users/jan/open-source/ember-intl/node_modules/rsvp/dist/rsvp.js:1017:35)
    at /Users/jan/open-source/ember-intl/node_modules/broccoli-persistent-filter/lib/strategies/persistent.js:55:18
    at tryCatch (/Users/jan/open-source/ember-intl/node_modules/async-disk-cache/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/Users/jan/open-source/ember-intl/node_modules/async-disk-cache/node_modules/rsvp/dist/rsvp.js:538:13)
    at publish (/Users/jan/open-source/ember-intl/node_modules/async-disk-cache/node_modules/rsvp/dist/rsvp.js:508:7)
    at flush (/Users/jan/open-source/ember-intl/node_modules/async-disk-cache/node_modules/rsvp/dist/rsvp.js:2415:5)
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
```

Let me know, if there's any more info you need or whether I can do anything else to help.

**Comment by rwjblue** [comment]
Should be fixed on https://github.com/emberjs/ember.js/pull/19320 lands.

**Comment by rwjblue** [comment]
@buschtoens - Took me a minute in tracking this down due to a mismatch in what was actually running vs what seemed to be running.

The original report was RE: `{{@component.name}}`, but the actual code being ran in ember-intl's test suite was `{{component.name}}`. The ember-cli-addon-docs template was updated only recently to migrate from `{{component.name}}` to `{{@component.name}}` (in https://github.com/ember-learn/ember-cli-addon-docs/commit/9bab07c5a99f3ecff4c31ea981c51921b6ce2552).

**Comment by buschtoens** [comment]
omg 🤦🏼‍♂️
Sorry for wasting your time!

I'll verify, once the fix lands in canary. 😇
Thank you.

**Comment by rwjblue** [comment]
Now that the fix has landed, I've submitted https://github.com/ember-intl/ember-intl/pull/1482 to reenable canary testing on ember-intl.
