### ISSUE TITLE
[Bug] Could not find module `ember-testing` imported from `@ember/test/index` on ember 3.27.0

### ISSUE THREAD

**Issue by sinankeskin** [emberjs/ember.js#19538]
### 🐞 Describe the Bug
Updating ember app to v3.27.0 causing an error: Could not find module `ember-testing` imported from `@ember/test/index`

### 🔬 Minimal Reproduction
Create an app with latest `ember-cli`. Update `ember-source` to v3.27.0
Build the app with `npm run build`. Go to dist folder. Serve the folder. In my case, I'm using `python -m "http.server"`
You'll see the error message as: Uncaught Error: Could not find module `ember-testing` imported from `@ember/test/index`

I'm seeing the same error with my production app.

Here is the sample [repo](https://github.com/sinankeskin/ember327).

### 😕 Actual Behavior
App successfully built but when I run and reach to main route I'm seeing this error and app doesn't work.

### 🤔 Expected Behavior
App should be working.

### 🌍 Environment

- Ember: - 3.26.1
- Node.js/npm: - v14.16.1/7.6.3
- OS: - Windows 10
- Browser: - Microsoft Edge  90.0.818.51 x64

**Comment by kpfefferle** [comment]
We are also seeing this error when we try to run our production app builds.

**Comment by elwayman02** [comment]
https://github.com/embroider-build/embroider/issues/805 seems to be related as well. I encountered the exact same error on Ember 3.26, but when upgrading `@embroider/test-setup` instead.

**Comment by runspired** [comment]
@elwayman02 most of the embroider ones are due to a bad fix in ember-cli-babel for https://github.com/ember-polyfills/ember-cached-decorator-polyfill/issues/70

**Comment by pzuraq** [comment]
This should be fixed in 3.27.1, let us know if there are any issues!

**Comment by sinankeskin** [comment]
I confirm, this issue fixed with 3.27.1

Thanks a lot.

**Comment by ascudder** [comment]
I'm using Ember 3.28.12 and I encounter this error if I turn on `staticEmberSource` in my embroider configuration. Is there a reason this would have regressed, or is there possibly an incorrect transitive dependency I should track down?

For more context, here are the embroider versions I'm using:

```
@embroider/compat: 3.7.0
@embroider/core: 3.4.19
@embroider/test-setup: 4.0.0
@embroider/webpack: 4.0.8
```

**Comment by NullVoxPopuli** [comment]
does the error persist if you update `@embroider/shared-internals` (check lockfile) to at least 2.8.1?
